name: "Validate Terraform Paths"

on:
  pull_request:
    branches:
      - main
    paths:
      - infrastructure/modules/**
  push:
    branches:
      - main
    paths:
      - infrastructure/modules/**

jobs:
  changed_files:
    name: Changed files
    runs-on: ubuntu-latest
    outputs:
      changed_paths: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          path: 'infrastructure/modules'
          dir_names_max_depth: 1
          matrix: true

  validate_terraform_paths:
    if: ${{ fromJson(needs.changed_files.outputs.changed_paths).length > 0 }}
    strategy:
      fail-fast: false
      matrix:
        module-paths: ${{ fromJson(needs.changed_files.outputs.changed_paths) }}
    needs:
      - changed_files
    runs-on: ubuntu-latest
    steps:
      - name: Echo paths
        run: |
          echo "changing path:"
          echo ${{ matrix.module-paths }}
        # with:
        #   module-path: ${{ matrix.module-paths }}
      - name: Validate path
        uses: ./validate-terraform/action.yaml
        with:
          module-path: ${{ matrix.module-paths }}
