name: "Validate Terraform Paths"

on:
  pull_request:
    branches:
      - main
    paths:
      - "infrastrucute/modules"
  push:
    branches:
      - main
    paths:
      - "infrastrucute/modules"

jobs:
  changed_files:
    name: "Changed files"
    runs-on: ubuntu-latest
    outputs:
      changed_paths: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          dir_names_max_depth: 4
          matrix: true

  validate_terraform_paths:
    if: ${{ fromJson(needs.changed_files.outputs.changed_paths).length > 0 }}
    strategy:
      fail-fast: false
      matrix:
        module-path: ${{ fromJson(needs.changed_files.outputs.changed_paths) }}
    needs:
      - changed_files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./validate-terraform/action.yaml
        with:
          module-path: ${{ matrix.module-path }}
